# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='my_points',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='their_points',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_answer_importance',
            field=models.CharField(max_length=50),
        ),
    ]
